### ISSUE TITLE
UncBudget GUI Copy causes crash

### ISSUE THREAD

**Issue by l-johnston** [wollmich/metas-unclib-python-wrapper#10]
Running the right_triangle.py example presents an uncertainty budget form (UncBudget) that has a Copy button. Pressing this Copy button raises an exception.
![image](https://user-images.githubusercontent.com/17813788/198110388-dad0cade-ff95-4090-b0ee-c731d089af57.png)

**Comment by wollmich** [comment]
This was a bug in the C# assembly. I fixed it. It will be part of the next release.
