### ISSUE TITLE
Add setup.cfg with dependencies

### ISSUE THREAD

**Issue by dasnessie** [wollmich/metas-unclib-python-wrapper#18]
I think the necessary dependencies should be automatically installed when installing your package via pip. This not only adds convenience for the user, but also provides better error output when system dependencies are missing, and saves your users from having to manually update their dependency lists across their projects should your dependencies change.

 Usually, that is done by adding the dependencies to a `setup.cfg` or a `pyproject.toml` file.

I'm not sure how you prepare the files for the pypi releases, otherwise I would have sent you a pull request to solve this issue. @BeSeeTek and I would be happy to help you prepare the necessary files if you're interested.

**Comment by wollmich** [comment]
I've modified now my setup files for the Linux and MacOS packages so that the `numpy` and `pythonnet` packages are installed.
For the windows package this was already the case.
This will be part of the next release V2.8.3.

**Comment by wollmich** [comment]
V2.8.3 has been released, see https://pypi.org/project/metas-unclib/2.8.3/.
