### ISSUE TITLE
Error when calculating power with negative ufloat base and positive ufloat exponent

### ISSUE THREAD

**Issue by dasnessie** [wollmich/metas-unclib-python-wrapper#19]
We noticed the following problem in python: 

```python
ufloat(-1)**3
-> -1.0 ± 0.0 #this is the expected result
ufloat(-1)**ufloat(3)
-> nan ± 0.0
ufloat(-1, 0.1)**ufloat(3, 0.2)
-> nan ± nan
```

It seems that calculating power with a negative ufloat base and a positive ufloat exponent always results in a `nan` result.
However, we ran the same calculations in MatLab and got:

```matlab
unc(-1,0.1,'Random')^unc(3,0.2,'Random')
-> -(1 ± 0.3000) + (3.6738e-16 ± 0.6283)i
```

**Comment by wollmich** [comment]
If your base is negative and you have positive float as exponent then the result will be complex. See the following example:

```
>>> a = ufloat(-1.0, 0.1)
>>> b = ufloat(3.0, 0.2)
>>> a**b
nan ± nan
>>> ucomplex(a)**b
(-1+3.673819061467132e-16j) ± (0.30000000000000004+0.6283185307179586j)
>>>
>>> umath.log(a)
nan ± 0.1
>>> umath.log(ucomplex(a))
3.141592653589793j ± (0.1+0j)
>>> umath.exp(b*umath.log(ucomplex(a)))
(-1+3.673819061467132e-16j) ± (0.30000000000000004+0.6283185307179586j)
```

The expected value of the imaginary part of the result is zero but not the uncertainty of it.

You need to convert the base from `ufloat` to `ucomplex` for negative values and float exponents.
The MATLAB Wrapper of METAS UncLib takes care about that. The Python wrapper doesn't.

The `pow` function is not the only one, the same problem exists as well for the `log`, `log10` and `sqrt` functions.

**Comment by dasnessie** [comment]
Ah, I see. I was expecting a behavior similar to what basic python does in these cases:

```python
(-2.0)**1.5
-> (-5.19573633741296e-16-2.8284271247461903j)
type((-2.0)**1.5)
-> <class 'complex'>
(-2.0)**3.0
-> -8.0
type((-2.0)**3.0)
-> <class 'float'>
```

Ie, when the result would be complex, return an object of type `complex`, and when it wouldn't, return an object of type `float`. I assume that it also what the Matlab wrapper does? Would you be open to a pull request that implements that behavior?

**Comment by wollmich** [comment]
> Would you be open to a pull request that implements that behavior?

I've added a pull request, see https://github.com/wollmich/metas-unclib-python-wrapper/pull/20, to fix this issue.
Can you test it as well on your side and report back.

**Comment by dasnessie** [comment]
Thank you! I've tested it, and it works exactly like I expected. I've created a pr to your new branch with the tests, in case you want to review them.
